### ISSUE TITLE
群晖在移动网络下只有ipv6，如何使用呀？

### ISSUE THREAD

**Issue by yaoniming-158** [BoscoL/AliDDNS#2]
亲爱的用户，您好：

任务计划程序已完成计划任务。

任务： Task 26
开始时间： Mon, 17 May 2021 22:09:10 GMT
结束时间： Mon, 17 May 2021 22:09:10 GMT
当前状态： 0 (正常)
标准输出/错误：

============================================================
Current OS: Linux x86_64 GNU/Linux
Current Time: 2021-05-17 22:09:10
============================================================

External IPv6: 

ERROR: DNS record value must be set, please use option: [-v | --value] to set it.

来自 DS918plus

**Comment by innns** [comment]
可以试试
`-v $(ip -6 address show | grep inet6 | awk '{print $2}' | cut -d'/' -f1)`
然后看看输出再grep一下 如
`-v $(ip -6 address show | grep inet6 | awk '{print $2}' | cut -d'/' -f1|grep "2409")`

**Comment by BoscoL** [comment]
使用v1.3.0以上版本。
